### ISSUE TITLE
Multiple timer update

### ISSUE THREAD

**Issue by DoktorSAS** [cavdarfurkan/pie_timer#1]
## Flickering effect with multiple timers

Im working on an app that can have more then one timer. I like this PieTimer and i would like to make it work but seems that every "Tick" all the pie timers get updated and the flick on the ui

https://user-images.githubusercontent.com/62484597/189887386-3bc91d9d-93b5-40d6-9fdf-1189fbf37933.mp4

## Code

This is how the code generate the timers. I have a list of `PieAnimationController` called `pieControllers`, so i can have a `PieAnimationController` for each timer. I generate a timer for each index. 

```dart
PieTimer(
              pieAnimationController: pieControllers[timerIndex],
              duration: Duration(hours: widget.hours, minutes: widget.minutes, seconds: widget.seconds),
              radius: pieSize,
              fillColor: pieColors[timerIndex],
              pieColor: Colors.black38,
              borderColor: Colors.black87,
              borderWidth: 3,
              shadowColor: Colors.black87,
              shadowElevation: 15.0,
              textStyle: TextStyle(
                color: Colors.white,
                fontSize: pieSize.toDouble()/2,
                fontWeight: FontWeight.w700,
              ),
              isReverse: false,
              onCompleted: () => {},
              onDismissed: () => {},
              enableTouchControls: true,
            )
```

# Note

I try to edit the lib to see where could be the cause but i can't find it. I tought was caused by the opacity but seems to don't be the cause.

**Comment by DoktorSAS** [comment]
# Note
After a more thorough investigation, I found where the problem stees to came from. The `addListener` is called for each change of the object, for 10 seconds ti timer is called 1500 times. If i call it after 100 times the issue will not appear.

**Comment by cavdarfurkan** [comment]
Thank you for pointing out the bug. Turned out it was caused by using the same path in the **PiePainter** for both **background circle** and **hitTest**. I fixed it and soon will publish the new version as v1.1.1.
